// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scoreboard.sql

package db

import (
	"context"
)

const getAllScoreboards = `-- name: GetAllScoreboards :many
SELECT id, name, createdat, updatedat FROM scoreboards
`

func (q *Queries) GetAllScoreboards(ctx context.Context) ([]Scoreboard, error) {
	rows, err := q.db.Query(ctx, getAllScoreboards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scoreboard
	for rows.Next() {
		var i Scoreboard
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Createdat,
			&i.Updatedat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
