// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Scoreboard struct {
	ID        int32
	Name      string
	Createdat sql.NullTime
	Updatedat sql.NullTime
}
